{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-app.fullname" . }}-backend-secret
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.backend.secrets.DATABASE_URL | quote }}
  OPEN_ROUTER_KEY: {{ .Values.backend.secrets.OPEN_ROUTER_KEY | quote }}
{{- end }}
