{{- if .Values.notificationService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-app.fullname" . }}-notification
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: notification
spec:
  type: {{ .Values.notificationService.service.type }}
  ports:
    - port: {{ .Values.notificationService.service.port }}
      targetPort: {{ .Values.notificationService.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "todo-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: notification
{{- end }}
